version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_DATABASE=contacts
      - MYSQL_USER=fazri
      - MYSQL_PASSWORD=fazri
    ports:
      - "3307:3306"
    volumes:
      - mysql-db:/var/lib/mysql
  mysqldb-quotes:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3308:3306"
    volumes:
      - mysql-db-quotes:/var/lib/mysql
volumes:
  mysql-db:
  mysql-db-quotes:
